Only add camera tasks when needed
heuristicus/spot_ros pull request #102
Opened 2023-02-15 11:54 UTC by maubrunn

I have noticed that we add all camera tasks in the beginning even if there is nothing subscribing to it. This slows down the frequencies of the camera topics a lot. I have added a routine that checks for subscribers to a camera topic and only then adds the task. I have also cleared up some minor bugs that I have come across when working with the driver. All is tested on our spot

2023-02-15 12:11 UTC, EricVoll requested changes

2023-02-15 12:11 UTC, EricVoll commented on spot_driver/src/spot_driver/spot_ros.py
> +        # self.hand_image_mono_pub
```suggestion

```

2023-02-15 12:11 UTC, EricVoll commented on spot_driver/src/spot_driver/spot_ros.py
> +            if pub.get_num_connections() > 0 and lookup[pub] not in self.added_tasks:
```suggestion
            if lookup[pub] not in self.added_tasks and pub.get_num_connections() > 0:
```
I'd expect the list search to be more efficient than the get_num_connections method.

2023-02-15 12:11 UTC, EricVoll commented on spot_driver/src/spot_driver/spot_ros.py
> +        pubs = [
The pub list and lookup dict can be defined outside of this function to avoid reinitialization at every `check_for_subscriber` call.

2023-02-15 12:11 UTC, EricVoll commented on spot_driver/src/spot_driver/spot_wrapper.py
> -            self._logger.info("Spot is powering on within the timeout of 20 secs")
Are these two lines removed on purpose?

2023-02-15 12:11 UTC, EricVoll commented on spot_driver/src/spot_driver/spot_wrapper.py
> +        lookup = {
define outside of function

2023-02-15 13:06 UTC, maubrunn commented on spot_driver/src/spot_driver/spot_wrapper.py
> -            self._logger.info("Spot is powering on within the timeout of 20 secs")
yes, if we try to power on spot when it is already powered on it crashes. Therefore I think it is okay to have the user power on spot manually before (or do it automatically via auto power on)

2023-02-15 15:31 UTC, EricVoll commented on spot_driver/src/spot_driver/spot_wrapper.py
> -            self._logger.info("Spot is powering on within the timeout of 20 secs")
Is there an API to check if it's powered on, and if not only then call the power on method?

2023-02-15 20:20 UTC, heuristicus commented on spot_driver/src/spot_driver/spot_ros.py
> +        self.lookup = {}
These variable names aren't clear about what they're doing. I suggest something like `active_camera_tasks` and `camera_pub_to_async_task_mapping`. Long descriptive names are totally fine in my view.

2023-02-15 20:21 UTC, heuristicus commented on spot_driver/src/spot_driver/spot_ros.py
> +            self.back_image_pub: "rear_image",
Add front image as well?

2023-02-15 20:22 UTC, heuristicus commented on spot_driver/src/spot_driver/spot_wrapper.py
> +            self.lookup = {
Also needs a better name. Perhaps `task_name_to_task_mapping` or something.

2023-02-15 20:25 UTC, heuristicus commented on spot_driver/src/spot_driver/spot_wrapper.py
> +        """Updates the async tasks for an image topic if there is a subscriber"""
I don't think this comment is actually true. From the perspective of spot_ros this might be true, but in this object subscribers don't exist. All we're doing is adding an async task based on the image name. Perhaps "Adds an async task to retrieve the images from the specified image source".

2023-02-15 20:31 UTC, heuristicus commented on spot_driver/src/spot_driver/spot_wrapper.py
> +        self._async_tasks.add_task(self.lookup[image_name])
Probably need guards here, check https://github.com/boston-dynamics/spot-sdk/blob/master/python/bosdyn-client/src/bosdyn/client/async_tasks.py#L26-L32 - it just appends the task to the list, not checking whether it's already there. I don't know if that is a problem, but it probably means that if this gets called multiple times the task would get executed multiple times.

2023-02-15 20:38 UTC, heuristicus commented on spot_driver/src/spot_driver/spot_ros.py
> +        self.lookup = {
```suggestion
        self.camera_pub_to_async_task_mapping = {
```

2023-02-15 20:42 UTC, heuristicus commented on spot_driver/src/spot_driver/spot_ros.py
> +                print("Adding :", self.lookup[pub])
```suggestion
        for pub in list(self.lookup.keys()):
            task_name = self.camera_pub_to_async_task_mapping[pub]
            if (
                task_name not in self.added_tasks
                and pub.get_num_connections() > 0
            ):
                self.spot_wrapper.update_image_tasks(task_name)
                self.active_camera_tasks.append(task_name)
                print(f"Detected subscriber for {task_name} task, adding task to publish")
```

Reusing the lookup a lot here, it's nicer to extract that to a variable.

2023-02-15 20:47 UTC, heuristicus commented on spot_driver/src/spot_driver/spot_wrapper.py
> -            self._logger.info("Spot is powering on within the timeout of 20 secs")
Probably use https://github.com/heuristicus/spot_ros/blob/bb82c29e9d51d12d57d53c8b4d4faecb600a1bc8/spot_driver/src/spot_driver/spot_wrapper.py#L1747-L1751

Not sure if this applies to the arm as well.

2023-02-16 14:50 UTC, maubrunn commented
I have addressed the comments and commited the changes, however I can not test the code at the moment. I think I will be able to do it next week and will merge then.

2023-02-22 10:57 UTC, maubrunn commented
I have tested everything on our spot again. It is now ready to merge in my opinion

2023-02-22 12:48 UTC, merged

2023-02-22 12:49 UTC, heuristicus commented
Thanks for the contribution.