Commands for the Arm and gripper, and URDF and simulation of the arm added
heuristicus/spot_ros pull request #67
Opened 2022-02-22 11:54 UTC by estherRay

I added a few commands to control the arm and the gripper using services for spot driver.
The services can be called as follow:
  rosservice call /spot/arm_stow "{}"
  rosservice call /spot/arm_unstow "{}"
  rosservice call /spot/gripper_open "{}"
  rosservice call /spot/gripper_close "{}"
  rosservice call /spot/gripper_angle_open "gripper_angle: 0.0"  (Open: -1.57; Close: 0.0)
  rosservice call /spot/arm_joint_move "joint_target: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]"  (Arm straight)

 I also added EricVoll code to visualize the gripper images in the driver.

The Spot-Arm folder contains the urdf of the arm, and simulation of the arm in MoveIt.

2022-02-22 12:31 UTC, heuristicus commented
Thanks for submitting the PR.

As a first look, I think we need to work out the best way of organising `spot_arm_description` and `spot_moveit_config`. Currently the spot's description is in `spot_description`. In my opinion it might be sensible to move the arm description stuff into that package, and set the xacro files up so that the arm can be included on the robot by using a parameter in the description launch file, something like

`spot_description/launch/spot_description.launch`
```
<launch>
  <arg name="use_arm" default="false"/>

  <param name="robot_description" command="$(find xacro)/xacro $(find spot_description)/urdf/spot.urdf.xacro use_arm:=$(arg use_arm)" />

  <node name="robot_state_publisher" pkg="robot_state_publisher" type="robot_state_publisher" />
</launch>
```

The current `spot.urdf.xacro` would then need something like (I can't remember the correct xacro commands, so this is more or less pseudocode)

```
<robot name="spot" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:arg name="use_arm" default="false" />
    if use_arm:
       <include spot_arm.urdf.xacro/>
       <joint name="body_to_arm_mount" type="fixed">
           <parent link="arm_parent_link" />
           <child link="arm_mount" />
       </joint>

```

2022-02-22 12:52 UTC, heuristicus commented on Spot-Arm/spot_arm_description/meshes/test
> +alo
Probably a forgotten file which isn't needed.

2022-02-22 12:55 UTC, heuristicus commented on README.md
>  # Spot ROS Driver
This should be consolidated, and further down in the readme, along with instructions on how to start the robot up with the arm.

2022-02-22 12:58 UTC, heuristicus commented on spot_driver/src/spot_driver/spot_wrapper.py
> +        return RobotCommandBuilder.build_synchro_command(arm_sync_robot_cmd)
Rename to `make_arm_trajectory_command` or similar to more clearly indicate what it does?

2022-02-22 13:01 UTC, heuristicus commented on spot_driver/src/spot_driver/spot_wrapper.py
> +            self._logger.info("Spot is powered off")
It should be possible to run all commands while the robot is running, and continue moving afterwards. Is there a reason for powering off here other than testing purposes?

2022-02-23 08:35 UTC, EricVoll commented on spot_driver/src/spot_driver/spot_wrapper.py
> +            assert self._robot.is_powered_on(), "Spot failed to power on"
```suggestion
            assert self._robot.is_powered_on(), "Spot failed to power on within the timeout of 25 secs"
```

2022-02-23 08:35 UTC, EricVoll commented on spot_driver/src/spot_driver/spot_wrapper.py
> +            time.sleep(2.0)
Why do we need the sleep here? If blocking_stand is actually blocking, then there should be no need for that, right? (Haven't tested it on the real robot yet, so maybe there is a reason)

2022-02-23 08:35 UTC, EricVoll commented on spot_driver/src/spot_driver/spot_wrapper.py
> +            return False, "Exception occured while arm was moving"
```suggestion
            return False, "Exception occured while trying to stow arm"
```

2022-02-23 08:35 UTC, EricVoll commented on spot_driver/src/spot_driver/spot_wrapper.py
> +            time.sleep(2.0)
Same question as with arm_stow here.

2022-02-23 08:35 UTC, EricVoll commented on spot_driver/src/spot_driver/spot_wrapper.py
> +            self._logger.info("Spot is powering on")
We could extract L758 to L763 into a function to reuse code. 
Something like `def ensure_power_and_stand`

2022-02-23 08:35 UTC, EricVoll commented on spot_driver/src/spot_driver/spot_wrapper.py
> +        if self._estop_client.get_status().stop_level != estop_pb2.ESTOP_LEVEL_NONE:
Why is the estop checked here? It isn't done in any other command (as far as I can see. For example the navigation command doesn't check the estop)

2022-02-23 10:31 UTC, estherRay commented
Thank you for the feedback. I will start making changes. A few things you commented on are for testing purposes, which I will remove / comment.

2022-02-23 13:04 UTC, estherRay commented on spot_driver/src/spot_driver/spot_wrapper.py
> +            self._logger.info("Spot is powered off")
This was for testing, I removed it

2022-02-23 13:05 UTC, estherRay commented on spot_driver/src/spot_driver/spot_wrapper.py
> +            time.sleep(2.0)
Some of the "sleep" were for testing, I removed them

2022-02-23 13:17 UTC, estherRay commented on spot_driver/src/spot_driver/spot_wrapper.py
> +        if self._estop_client.get_status().stop_level != estop_pb2.ESTOP_LEVEL_NONE:
It is node needed, this was for testing. I removed it now.

2022-02-23 13:24 UTC, heuristicus commented
@estherRay Could you convert this PR to a draft while we're still suggesting changes? You should be able to do it under the "reviewers" section on the right hand side.

2022-02-23 13:53 UTC, estherRay commented on spot_driver/src/spot_driver/spot_wrapper.py
> +            self._logger.info("Spot is powering on")
Created a method called check_arm_power_and_stand to do this

2022-02-25 08:50 UTC, EricVoll requested changes
Thanks for all adjustments. I'd do two additional changes marked as comments in the code. 
1. The "check_arm_power_and_stand" doesn't actually check the stand. Also I'd rename it to "ensure_..."
2. Since this method returns false if there is no arm, we have to check the output of the function in the service callbacks and exit early if no arm is present.

If these two thigs are fixed, we are ready to go and I'll add the PR for task-space control :)

2022-02-25 08:50 UTC, EricVoll commented on spot_driver/src/spot_driver/spot_wrapper.py
> +    def check_arm_power_and_stand(self):
```suggestion
    def ensure_arm_power_and_stand(self):
```

Does `self._robot.power_on` also cause spoto to stand up? If not, then I'd rename this function to `ensure_arm_and_robot_power` or something similar.

2022-02-25 08:50 UTC, EricVoll commented on spot_driver/src/spot_driver/spot_wrapper.py
> +            self.check_arm_power_and_stand()
```suggestion
            if not self.check_arm_power_and_stand():
                  return
```

Since check_arm_power_and_stand returns a boolean, we also have to exit the method here, if there is no arm.
Same with all other calls to this function in all Arm services.

2022-02-25 08:50 UTC, EricVoll commented on spot_driver/src/spot_driver/spot_wrapper.py
> +    def check_arm_power_and_stand(self):
```suggestion
    def check_arm_power_and_stand(self, stand_up = False):
           [CurrentCode]
            if not self._is_standing:
                self._logger.info("Commanding Spot to stand")
                robot_command.blocking_stand(command_client=self._robot_command_client,
                                             timeout_sec=10.0)
                self._logger.info("Spot standing")
            else:
                self._logger.info("Spot is already standing")
```

2022-02-25 10:32 UTC, estherRay commented on spot_driver/src/spot_driver/spot_wrapper.py
> +    def check_arm_power_and_stand(self):
Yes, this function makes spot stands as well. I just made the changes

2022-02-27 10:08 UTC, EricVoll requested changes
Ok, I think these are the last comments :)

2022-02-27 10:08 UTC, EricVoll commented on spot_driver/src/spot_driver/spot_wrapper.py
> +                self._logger.info(msg)
```suggestion
                self._logger.info(msg)
                return False, msg
```

Otherwise this method will return `True, "Opened gripper successfully` on line 927 because no Exception will be thrown. 
The same applies to all other methods. We'll need an early exit there as well.

2022-02-27 10:08 UTC, EricVoll commented on spot_driver/src/spot_driver/spot_wrapper.py
> +                self._logger.info(msg)
```suggestion
                self._logger.info(msg)
                return False, msg
```

2022-02-27 10:08 UTC, EricVoll commented on spot_driver/src/spot_driver/spot_wrapper.py
> +                self._logger.info(msg)
```suggestion
                self._logger.info(msg)
                return False, msg
```

2022-02-27 10:08 UTC, EricVoll commented on spot_driver/src/spot_driver/spot_wrapper.py
> +    def force_trajectory(self, forces:List[float], torques:List[float]):
This method doesn't seem to be used anywhere, as far as I can see. Can we delete it?

2022-02-27 10:08 UTC, EricVoll commented on spot_driver/src/spot_driver/spot_wrapper.py
> +                self._logger.info(msg)
```suggestion
                self._logger.info(msg)
                return False, msg
```

2022-02-27 10:08 UTC, EricVoll commented on spot_driver/src/spot_driver/spot_wrapper.py
> +                self._logger.info(msg)
```suggestion
                self._logger.info(msg)
                return False, msg
```

2022-02-27 10:08 UTC, EricVoll commented on spot_driver/src/spot_driver/spot_wrapper.py
> +                self._logger.info(msg)
```suggestion
                self._logger.info(msg)
                return False, msg
```

2022-02-27 10:08 UTC, EricVoll commented on spot_driver/src/spot_driver/spot_wrapper.py
> +                self._logger.info(msg)
```suggestion
                self._logger.info(msg)
                return False, msg
```

2022-02-28 12:03 UTC, estherRay commented on spot_driver/src/spot_driver/spot_wrapper.py
> +    def force_trajectory(self, forces:List[float], torques:List[float]):
I added the rest of the code needed to use this as a service

2022-03-01 13:46 UTC, EricVoll commented
@estherRay  awesome, thanks.
I'll test the code asap with our spot with arms. Hopefully this week (likely thursday)

2022-03-03 15:15 UTC, EricVoll commented
I tested the PR today and there are a few issues. Did you run the code on your spot? In my case there were a few issues.

1. There are indentation errors (some `try:` blocks in the spot_wrapper.py file)
2. The hand_pose service takes a float array instead of a Pose message as an input [ROS Pose](https://docs.ros.org/en/noetic/api/geometry_msgs/html/msg/Pose.html) and also hardcodes the quaternion
3. The joint space command service takes a float array as well, which is suboptimal because the length is variable. We could use `float[6] joint_angles` to fix the length of the array, or at least check the length of the array in the message and return a useful error message.

I fixed the indentation issues locally already and am happy to push them, but the changes are very small anyways.

2022-10-13 15:26 UTC, heuristicus commented
Closing this in favour of #85.

2022-10-13 15:26 UTC, closed without merging